In [1]:
# =========================================
# Amazon E-Commerce Data Cleaning Project
# =========================================

# Import Libraries

import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [2]:
# =========================================
# Connect MySQL Database
# =========================================

engine = create_engine(
    "mysql+pymysql://root:YourPassword@localhost/amazon_data"
)

In [3]:
# =========================================
# Load Tables
# =========================================

orders = pd.read_sql("SELECT * FROM orders LIMIT 5", engine)

products = pd.read_sql("SELECT * FROM products LIMIT 5", engine)

customers = pd.read_sql("SELECT * FROM customers LIMIT 5", engine)

sellers = pd.read_sql("SELECT * FROM sellers LIMIT 5", engine)

payments = pd.read_sql("SELECT * FROM payments LIMIT 5", engine)

category = pd.read_sql("SELECT * FROM category LIMIT 5", engine)

reviews = pd.read_sql("SELECT * FROM reviews LIMIT 5", engine)

In [4]:
# =========================================
# Check Real Columns
# =========================================

print("Orders Columns:")
print(orders.columns)

print("\nProducts Columns:")
print(products.columns)

print("\nCustomers Columns:")
print(customers.columns)

print("\nSellers Columns:")
print(sellers.columns)

print("\nPayments Columns:")
print(payments.columns)

print("\nCategory Columns:")
print(category.columns)

print("\nReviews Columns:")
print(reviews.columns)

Orders Columns:
Index(['order_id', 'customer_key', 'product_key', 'seller_key', 'payment_id',
       'purchase_date', 'shipping_time_days', 'is_returned', 'delivery_status',
       'seller_rating'],
      dtype='object')

Products Columns:
Index(['product_key', 'product_id', 'category_id', 'brand', 'price',
       'discount', 'final_price', 'stock', 'rating', 'review_count'],
      dtype='object')

Customers Columns:
Index(['customer_key', 'customer_id', 'location', 'device'], dtype='object')

Sellers Columns:
Index(['seller_key', 'seller_id', 'seller_rating'], dtype='object')

Payments Columns:
Index(['payment_id', 'payment_method'], dtype='object')

Category Columns:
Index(['category_id', 'category_name', 'subcategory'], dtype='object')

Reviews Columns:
Index(['review_id', 'customer_key', 'product_key', 'rating', 'review_count'], dtype='object')

In [5]:
Index(['customer_key','customer_id'], dtype='object')

NameError: name 'Index' is not defined

In [6]:
# =========================================
# Create Master Analytical Dataset
# =========================================

query = """

SELECT
    o.order_id,
    o.purchase_date,
    o.shipping_time_days,
    o.is_returned,
    o.delivery_status,
    o.seller_rating,

    c.customer_id,

    p.product_id,
    p.brand,
    p.price,
    p.final_price,
    p.rating AS product_rating,
    p.review_count,

    cat.category_name,

    s.seller_id,

    pay.payment_method

FROM orders o

LEFT JOIN customers c
ON o.customer_key = c.customer_key

LEFT JOIN products p
ON o.product_key = p.product_key

LEFT JOIN category cat
ON p.category_id = cat.category_id

LEFT JOIN sellers s
ON o.seller_key = s.seller_key

LEFT JOIN payments pay
ON o.payment_id = pay.payment_id

"""

In [7]:
# =========================================
# Load Final Analytical Dataset
# =========================================

merged_df = pd.read_sql(query, engine)

merged_df.head()

,order_id,purchase_date,shipping_time_days,is_returned,delivery_status,seller_rating,customer_id,product_id,brand,price,final_price,product_rating,review_count,category_name,seller_id,payment_method
0,1,2025-03-04,6,1,Returned,4.3,U356787,P39256,H&M,33090.51,29629.31,4.9,43,Electronics,S2679,UPI
1,2,2025-12-12,1,1,Returned,4.9,U198246,P38657,Samsung,9368.97,8870.73,3.9,13,Sports,S9279,UPI
2,3,2024-04-25,1,1,Returned,4.9,U539898,P38893,H&M,14756.85,10919.43,4.2,46,Sports,S5557,Credit Card
3,4,2025-12-18,2,0,In Transit,3.1,U325772,P54118,Sony,668.83,502.91,3.8,6,Beauty,S2519,UPI
4,5,2024-05-16,5,0,Delayed,2.6,U865179,P70217,Sony,10881.29,5589.58,4.0,48,Home,S3045,UPI

In [8]:
# =========================================
# Dataset Information
# =========================================

merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 16 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   order_id            1000000 non-null  int64
 1   purchase_date       1000000 non-null  object
 2   shipping_time_days  1000000 non-null  int64
 3   is_returned         1000000 non-null  object
 4   delivery_status     1000000 non-null  object
 5   seller_rating       1000000 non-null  float64
 6   customer_id         1000000 non-null  object
 7   product_id          1000000 non-null  object
 8   brand               1000000 non-null  object
 9   price               1000000 non-null  float64
 10  final_price         1000000 non-null  float64
 11  product_rating      1000000 non-null  float64
 12  review_count        1000000 non-null  int64
 13  category_name       1000000 non-null  object
 14  seller_id           1000000 non-null  object
 15  payment_method      1000000 non-null  object
dtypes: float64(4), int64(3), object(9)
memory usage: 122.1+ MB

In [9]:
# =========================================
# Missing Values
# =========================================

merged_df.isnull().sum()

order_id              0
purchase_date         0
shipping_time_days    0
is_returned           0
delivery_status       0
seller_rating         0
customer_id           0
product_id            0
brand                 0
price                 0
final_price           0
product_rating        0
review_count          0
category_name         0
seller_id             0
payment_method        0
dtype: int64

In [10]:
# =========================================
# Remove Duplicate Records
# =========================================

merged_df.drop_duplicates(inplace=True)

In [11]:
# =========================================
# Delivery Delay Feature
# =========================================

merged_df["delivery_delay"] = (
    merged_df["shipping_time_days"] > 5
).astype(int)

In [12]:
# =========================================
# Extract Year and Month
# =========================================

merged_df["purchase_date"] = pd.to_datetime(
    merged_df["purchase_date"]
)

merged_df["year"] = merged_df["purchase_date"].dt.year

merged_df["month"] = merged_df["purchase_date"].dt.month

In [13]:
# =========================================
# Save Clean Dataset
# =========================================

merged_df.to_csv(
    "clean_amazon_data.csv",
    index=False
)

In [14]:
merged_df

,order_id,purchase_date,shipping_time_days,is_returned,delivery_status,seller_rating,customer_id,product_id,brand,price,final_price,product_rating,review_count,category_name,seller_id,payment_method,delivery_delay,year,month
0,1,2025-03-04,6,1,Returned,4.3,U356787,P39256,H&M,33090.51,29629.31,4.9,43,Electronics,S2679,UPI,1,2025,3
1,2,2025-12-12,1,1,Returned,4.9,U198246,P38657,Samsung,9368.97,8870.73,3.9,13,Sports,S9279,UPI,0,2025,12
2,3,2024-04-25,1,1,Returned,4.9,U539898,P38893,H&M,14756.85,10919.43,4.2,46,Sports,S5557,Credit Card,0,2024,4
3,4,2025-12-18,2,0,In Transit,3.1,U325772,P54118,Sony,668.83,502.91,3.8,6,Beauty,S2519,UPI,0,2025,12
4,5,2024-05-16,5,0,Delayed,2.6,U865179,P70217,Sony,10881.29,5589.58,4.0,48,Home,S3045,UPI,0,2024,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999996,2025-03-12,1,0,Delivered,4.2,U485987,P55818,Nike,40654.37,35526.07,4.2,19,Electronics,S7795,Credit Card,0,2025,3
999996,999997,2025-11-04,5,0,In Transit,3.6,U917934,P59467,Apple,872.33,700.55,3.7,2,Sports,S4919,Debit Card,0,2025,11
999997,999998,2025-11-06,5,0,In Transit,2.8,U667215,P21840,H&M,3361.11,2011.55,3.7,9,Clothing,S4196,Debit Card,0,2025,11
999998,999999,2025-02-25,1,0,Delivered,2.9,U640883,P46092,Adidas,1744.01,1221.04,3.1,56,Sports,S3812,Debit Card,0,2025,2
999999,1000000,2025-05-28,5,0,Delayed,2.8,U220301,P91830,Samsung,680.56,271.78,4.1,47,Clothing,S1286,UPI,0,2025,5